---
- hosts: rabbitmq
  become: yes
  gather_facts: no
  tasks:
    - name: ensure trusted key is added
      apt_key:
        url: 'https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc'
        state: present
    - name: ensure rabbitmq repositories are added
      apt_repository:
        repo: '{{ item }}'
        state: present
      with_items:
        - 'deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang'
        - 'deb https://dl.bintray.com/rabbitmq/debian/ bionic main'
    - name: ensure package is installed
      apt:
        name: rabbitmq-server
    - name: ensure rabbitmq plugins are installed
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - restart rabbitmq
  handlers:
    - name: restart rabbitmq
      service:
        name: rabbitmq-service
        state: restarted

- hosts: rabbitmq
  become: yes
  gather_facts: no
  vars:
    user: ads
    password: 3rfscdscsfSDF
  tasks:
    - name: ensure rabbitmq user is present
      rabbitmq_user:
        user: '{{ user }}'
        password: '{{ password }}'
        tags: administrator
        vhost: /
        configure_priv: .*
        write_priv: .*
        read_priv: .*
        state: present
    - name: ensure guest user is absent
      rabbitmq_user:
        user: guest
        state: absent
