---
- name: pull image on remote
  become: yes
  docker_image:
    name: docker.elastic.co/kibana/kibana-oss:7.8.0
    source: pull

- name: run docker container
  become: yes
  environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana-oss:7.8.0
    detach: yes
    auto_remove: no
    ports:
      - "5601:5601"
    restart_policy: on-failure
    restart_retries: 10
    state: started
