---
- name: pull image on remote
  become: yes
  docker_image:
    name: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    source: pull

- name: ensure config directory is created
  file:
    path: /usr/share/elasticsearch/config
    state: directory

- name: ensure config is uploaded
  copy:
    src: elasticsearch.yml
    dest: /usr/share/elasticsearch/config/elasticsearch.yml

- name: run docker container
  become: yes
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    detach: yes
    auto_remove: no
    ports:
      - "9200:9200"
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
      - /usr/share/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    restart_policy: on-failure
    restart_retries: 10
    state: started
